version: '3'

services:
  neo4j:
    # build: ./neo4j
    build: 
      context: ./neo4j
      args:
        # NEO4JLABS_PLUGINS: '["apoc"]'
        APOC_VERSION:
        NEO4J_VERSION:
        NEO4J_AUTH: 
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_allow__format__migration=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4JLABS_PLUGINS='["graph-data-science", "apoc"]'
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j://localhost:7687
    volumes:
      - ./conf:/conf

  api:
    build: ./backend
    ports:
      - 8000:8000 # api endpoint
      - 8001:8001
      - 8265:8265 # ray dashboard
      - 10001:10001 # ray client
    volumes:
      - ./backend:/app
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_AUTH=${NEO4J_AUTH}
      - RAY_ADDRESS=auto
    # command: python /app/app/main.py # 
    # command: uvicorn app.main:app --host 0.0.0.0 --reload
    command: 'bash /app/entrypoint.sh'
    depends_on:
      - neo4j

  ui:
    build: ./web-react
    ports:
      - 3000:3000
    environment:
      - CI=true
      - REACT_APP_GRAPHQL_URI=/graphql
      # - REACT_APP_GRAPHQL_URI=http://0.0.0.0:3000/graphql
      - PROXY=http://api:4001/graphql
      # - REACT_APP_API_HOST=http://api:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    volumes:
      - ./web-react/src:/app/src